/**
 * This file was generated by the Jeddict
 */
package com.gudpick.trial.entity;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

/**
 * @author Indu
 */
@Entity
public class Student {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String first_name;

    @Basic
    private String last_name;

    @ManyToMany(targetEntity = Courses.class, mappedBy = "students")
    private List<Courses> courseses;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirst_name() {
        return this.first_name;
    }

    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    public String getLast_name() {
        return this.last_name;
    }

    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

    public List<Courses> getCourseses() {
        return this.courseses;
    }

    public void setCourseses(List<Courses> courseses) {
        this.courseses = courseses;
    }

}